[book]
authors = ["Triton Software AG"]
language = "en"
src = "src"
title = "Triton VM"

[preprocessor.katex]

[output.html]
git-repository-url = "https://github.com/TritonVM/triton-vm/tree/master/specification"
additional-css = ["custom.css"]
