on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Rust

jobs:
  build:
    name: Build, lint, test, bench, coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.7, 2020-03-24
        with:
          profile: minimal
          toolchain: stable
          override: true

      # We always build with latest stable, but we also reset
      # the CI cache when new versions of Rust are released.
      - name: Determine build cache key
        id: vars
        run: |
          RUST_VERSION=$(rustc -V | grep -Po '(?<=^rustc )\S+')
          echo "rustc-version=$RUST_VERSION" >> $GITHUB_OUTPUT

      # 1. Use `**/Cargo.toml` in cache key because Cargo.lock isn't committed.
      # 2. Don't include target/ -- only cache building 3rd-party libraries.
      - name: Use build cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # v3.0.11, 2022-10-13
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.vars.outputs.rustc-version }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Build constraints
        run: make build-constraints

      - name: Run fmt
        run: make fmt-only

      - name: Run clippy
        run: make clippy-only

      - name: Run tests
        run: cargo test --all-targets

      - name: Run benchmarks
        run: cargo bench --all-targets
